### ISSUE TITLE
Disallow non StyleModule or String values

### ISSUE THREAD

**Issue by LarsDenBakker** [bashmish/lit-css#4]
Currently `css` concatenates non-StyleModule. This will `toString` values and lead to invalid CSS. In my case the subsequent value is passed to shady css which then causes an infinite loop and crashes the page. It was a difficult bug to track down.

I think it makes sense for `css` to throw an error on non StyleModule or String (perhaps also allow Number?) values to help developers.

**Comment by bashmish** [comment]
Is was busy with setting up the monorepo here and releasing StyledLitElement. Will look into this tonight, hopefully.
