### ISSUE TITLE
Does not work with TypeScript decorator

### ISSUE THREAD

**Issue by koliyo** [bashmish/lit-css#6]
```ts
@customElement('brick-model-form')
export class BrickModelForm extends StyledLitElement {
```

gives

```
Argument of type 'typeof BrickModelForm' is not assignable to parameter of type 'ClassDescriptor | Constructor<HTMLElement>'.
  Type 'typeof BrickModelForm' is not assignable to type 'Constructor<HTMLElement>'.
    Type 'BrickModelForm' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 237 more.ts(2345)
```

Using the standard `LitElement` does not give this problem.

**Comment by koliyo** [comment]
Sidenote, what is the advantage of `StyledLitElement` compared to https://lit-element.polymer-project.org/guide/styles#static-styles ?

**Comment by bashmish** [comment]
I think as of now there is no need to use StyledLitElement, just use LitElement's mechanism for writing styles.

If you are still interested in using StyledLitElement for some reason, please reopen, so that I can take a look at your issue.
